// Standees: painted die-cut "paper mini" cutouts for people. The card is planted
// at the figure's facing and leans toward the camera (never spinning fully, so
// the figure still visibly faces where it faces); past side-on it flips to show
// its rear face, or the mirrored front when there is no rear art. Two triangles
// per person, alpha-tested so shadows follow the silhouette.
//
// Art comes from a library generated by scripts/scene-pipeline/standee-library.ts
// and served from public/standees/<setting>/.

import * as THREE from "three"
import type { Animated } from "../atmosphere"
import type { Rng } from "../core"

export type StandeePose = "standing" | "seated"

export interface StandeeLibraryEntry {
  id: string
  pose: StandeePose
  height: number
  aspect: number
  back?: boolean
}

export interface StandeeArt extends StandeeLibraryEntry {
  front: THREE.Texture
  rear: THREE.Texture | null
}

export class StandeeLibrary {
  private constructor(
    readonly baseUrl: string,
    readonly entries: Map<string, StandeeArt>
  ) {}

  /** Fetch library.json and every texture it lists. */
  static async load(baseUrl: string): Promise<StandeeLibrary> {
    const response = await fetch(`${baseUrl}/library.json`)
    if (!response.ok) throw new Error(`standee library not found at ${baseUrl} (${response.status})`)
    const list = (await response.json()) as StandeeLibraryEntry[]
    const loader = new THREE.TextureLoader()
    const load = async (url: string) => {
      const texture = await loader.loadAsync(url)
      texture.colorSpace = THREE.SRGBColorSpace
      texture.anisotropy = 8
      return texture
    }
    const entries = new Map<string, StandeeArt>()
    await Promise.all(
      list.map(async (entry) => {
        const [front, rear] = await Promise.all([load(`${baseUrl}/${entry.id}.png`), entry.back ? load(`${baseUrl}/${entry.id}-back.png`) : Promise.resolve(null)])
        entries.set(entry.id, { ...entry, front, rear })
      })
    )
    return new StandeeLibrary(baseUrl, entries)
  }

  get(id: string): StandeeArt {
    const art = this.entries.get(id)
    if (!art) throw new Error(`no standee "${id}" in ${this.baseUrl}`)
    return art
  }

  /** All ids with the given pose, optionally excluding some (named NPCs). */
  ids(pose: StandeePose, exclude: (id: string) => boolean = (id) => id.startsWith("npc-")): string[] {
    return [...this.entries.values()].filter((e) => e.pose === pose && !exclude(e.id)).map((e) => e.id)
  }

  pick(rng: Rng, pose: StandeePose): StandeeArt {
    const ids = this.ids(pose)
    if (!ids.length) throw new Error(`standee library has no ${pose} figures`)
    return this.get(rng.pick(ids))
  }

  dispose() {
    for (const art of this.entries.values()) {
      art.front.dispose()
      art.rear?.dispose()
    }
  }
}

const MAX_LEAN = THREE.MathUtils.degToRad(60)
const FLIP_TO_BACK = THREE.MathUtils.degToRad(100)
const FLIP_TO_FRONT = THREE.MathUtils.degToRad(80)
const wrapAngle = (a: number) => Math.atan2(Math.sin(a), Math.cos(a))

interface Card {
  pivot: THREE.Group
  facing: number
  behind: boolean
}

function cardMaterial(texture: THREE.Texture, doubleSided: boolean): THREE.MeshStandardMaterial {
  return new THREE.MeshStandardMaterial({
    map: texture,
    emissiveMap: texture,
    emissive: 0xffffff,
    emissiveIntensity: 0.3,
    alphaTest: 0.5,
    side: doubleSided ? THREE.DoubleSide : THREE.FrontSide,
    roughness: 0.6,
  })
}

function depthMaterial(texture: THREE.Texture): THREE.MeshDepthMaterial {
  return new THREE.MeshDepthMaterial({ map: texture, alphaTest: 0.5, depthPacking: THREE.RGBADepthPacking })
}

/**
 * Owns every standee in a set: builds cards and leans them toward the camera
 * each frame. Push it into the set's `animated`.
 */
export class StandeeSystem implements Animated {
  private readonly cards: Card[] = []
  private readonly worldPosition = new THREE.Vector3()

  /**
   * A card for `art`, feet at the group's origin, planted at `facing` (yaw
   * radians, 0 = +Z). Returns the outer group to position in the set.
   */
  add(art: StandeeArt, { facing = 0, height }: { facing?: number; height?: number } = {}): THREE.Group {
    const h = height ?? art.height
    const w = h * art.aspect
    const outer = new THREE.Group()
    outer.rotation.y = facing
    const pivot = new THREE.Group()
    outer.add(pivot)
    const rearWidth = art.rear ? h * art.aspect : w

    const edge = new THREE.Mesh(new THREE.PlaneGeometry(w, h), new THREE.MeshStandardMaterial({ map: art.front, color: 0x141210, alphaTest: 0.4, side: THREE.DoubleSide, roughness: 0.8 }))
    edge.position.y = h / 2
    edge.scale.set(1.04, 1.025, 1)
    pivot.add(edge)

    const front = new THREE.Mesh(new THREE.PlaneGeometry(w, h), cardMaterial(art.front, !art.rear))
    front.position.set(0, h / 2, 0.008)
    front.castShadow = true
    front.customDepthMaterial = depthMaterial(art.front)
    pivot.add(front)

    if (art.rear) {
      const rear = new THREE.Mesh(new THREE.PlaneGeometry(rearWidth, h), cardMaterial(art.rear, false))
      rear.position.set(0, h / 2, -0.008)
      rear.rotation.y = Math.PI
      rear.castShadow = true
      rear.customDepthMaterial = depthMaterial(art.rear)
      pivot.add(rear)
    }
    this.cards.push({ pivot, facing, behind: false })
    return outer
  }

  update(_t: number, dt: number, camera?: THREE.Camera) {
    if (!camera) return
    const k = Math.min(1, 1 - Math.exp(-10 * dt))
    for (const card of this.cards) {
      card.pivot.getWorldPosition(this.worldPosition)
      const camYaw = Math.atan2(camera.position.x - this.worldPosition.x, camera.position.z - this.worldPosition.z)
      // The outer group already carries `facing`, so the lean is relative to it.
      const parentYaw = card.pivot.parent ? yawOf(card.pivot.parent) : card.facing
      const off = wrapAngle(camYaw - parentYaw)
      if (card.behind ? Math.abs(off) < FLIP_TO_FRONT : Math.abs(off) > FLIP_TO_BACK) card.behind = !card.behind
      const target = card.behind ? THREE.MathUtils.clamp(wrapAngle(off - Math.PI), -MAX_LEAN, MAX_LEAN) + Math.PI : THREE.MathUtils.clamp(off, -MAX_LEAN, MAX_LEAN)
      card.pivot.rotation.y += wrapAngle(target - card.pivot.rotation.y) * k
    }
  }
}

const _q = new THREE.Quaternion()
const _e = new THREE.Euler()
/** World yaw of an object, from its world quaternion. */
function yawOf(object: THREE.Object3D): number {
  object.getWorldQuaternion(_q)
  _e.setFromQuaternion(_q, "YXZ")
  return _e.y
}
