// Set: the common room of the Dragonbone Inn, Kordavos — a double-height
// Valkaran timber hall at early evening, crowded for the Harvest Festival.
// Authored from out/scene-pipeline/the-dragonbone-inn/brief.md against scene-kit.
//
// Encounters: the-dragonbone-inn, morning-at-the-dragonbone (march-of-davos).
//
// Layout (metres): x -9..9, z -14..14, ceiling 7. North (+z) is the street:
// double doors and two leaded windows. South (-z) is the great hearth and the
// bard's dais. East (+x) is the bar with the cask rack and the kitchen pass.
// West (-x) is the gallery with the stair at its north end and the party's
// snug tucked beneath it.

import * as THREE from "three"
import {
  type BuilderContext,
  barCounter,
  barrel,
  bench,
  box,
  bunting,
  createEnvironment,
  doubleDoor,
  ENVIRONMENT_PRESETS,
  flatGround,
  gallery,
  harvestDressing,
  hearth,
  highBackBench,
  hostStand,
  kitchenPass,
  leadedWindow,
  roomShell,
  type SceneSet,
  type SetContext,
  type SetDefinition,
  StandeeLibrary,
  StandeeSystem,
  staircase,
  tableClutter,
  trestleTable,
  V3,
  wallSconce,
  wheelChandelier,
} from "@/lib/scene-kit"

const W = 18
const D = 28
const H = 7
/** Painted people: crowd types and Bram, generated by scripts/scene-pipeline/standee-library.ts. */
const STANDEES = "/standees/realm-of-myr"

async function build(ctx: SetContext): Promise<SceneSet> {
  const { scene, renderer, time, rng, materials: M, fire, toggles, progress } = ctx
  const b: BuilderContext = { materials: M, rng, time, fire }
  const root = new THREE.Group()
  const animated: SceneSet["animated"] = [fire]
  const night = toggles.timeOfDay === "night"
  const place = (object: THREE.Object3D, x: number, z: number, ry = 0, y = 0, parent: THREE.Object3D = root) => {
    object.position.set(x, y, z)
    object.rotation.y = ry
    parent.add(object)
    return object
  }

  const environment = createEnvironment(scene, renderer, time, night ? ENVIRONMENT_PRESETS.interiorNight : ENVIRONMENT_PRESETS.interiorDusk)
  await progress("Painting the crowd…")
  const standees = await StandeeLibrary.load(STANDEES)
  const people = new StandeeSystem()
  animated.push(people)
  /** A standee with its feet at (x, y, z), planted at `facing` (yaw radians, 0 = +Z). */
  const person = (id: string, x: number, z: number, facing: number, y = 0, parent: THREE.Object3D = root) => place(people.add(standees.get(id), { facing }), x, z, 0, y, parent)
  const someone = (pose: "standing" | "seated", x: number, z: number, facing: number, y = 0, parent: THREE.Object3D = root) =>
    place(people.add(standees.pick(rng, pose), { facing }), x, z, 0, y, parent)
  const outside = night ? null : 0x4a5f8f
  const windowLight = night ? null : { color: 0x6f8fd6, intensity: 40 }

  // ---- shell ---------------------------------------------------------------
  await progress("Raising the hall…")
  root.add(
    roomShell(b, {
      width: W,
      depth: D,
      height: H,
      openings: {
        north: [
          { x0: -1.4, x1: 1.4, y0: 0, y1: 3.2 },
          { x0: -7.2, x1: -4.8, y0: 2.2, y1: 5.2 },
          { x0: 4.8, x1: 7.2, y0: 2.2, y1: 5.2 },
        ],
        east: [
          { x0: -9, x1: -6, y0: 1.0, y1: 3.2 },
          { x0: 6, x1: 8.4, y0: 2.2, y1: 5.2 },
        ],
        west: [{ x0: -12, x1: -9.6, y0: 2.2, y1: 5.2 }],
      },
      floor: "plank",
      postSpacing: 4,
      beamSpacing: 4,
    })
  )
  place(doubleDoor(b, { w: 2.8, h: 3.2, outside }), 0, D / 2, Math.PI)
  place(leadedWindow(b, { w: 2.4, h: 3.0, light: windowLight }), -6, D / 2, Math.PI, 3.7)
  place(leadedWindow(b, { w: 2.4, h: 3.0, light: windowLight }), 6, D / 2, Math.PI, 3.7)
  place(leadedWindow(b, { w: 2.4, h: 3.0, light: windowLight }), W / 2, 7.2, -Math.PI / 2, 3.7)
  place(leadedWindow(b, { w: 2.4, h: 3.0, light: windowLight }), -W / 2, -10.8, Math.PI / 2, 3.7)

  // ---- hearth end ----------------------------------------------------------
  await progress("Lighting the hearth…")
  place(hearth(b, { width: 4.5, height: 3.5, depth: 1.5, ceilingHeight: H }), 2, -D / 2 + 0.75)
  const dais = new THREE.Group()
  place(dais, -5, -12.4)
  dais.add(box(2.6, 0.22, 2.0, M.wood(3, 2, M.woodTex), 0, 0.11, 0))
  person("bard-lute", 0, 0, 0.35, 0.22, dais)

  // ---- bar end -------------------------------------------------------------
  await progress("Stocking the bar…")
  place(barCounter(b, { length: 8 }), 7.2, 0, -Math.PI / 2)
  place(kitchenPass(b, { w: 3, h: 2.2, sill: 1.0 }), W / 2, -7.5, -Math.PI / 2)
  for (const [x, z, ry] of [
    [7.8, -5.2, 0.3],
    [8.1, -4.4, 1.2],
    [7.6, 11.5, 0.6],
    [8.3, 12.4, 2.0],
  ])
    place(barrel(b), x, z, ry, 0.4)
  const stacked = barrel(b)
  stacked.position.set(7.9, 1.2, 12.0)
  root.add(stacked)

  // ---- gallery, stair, snug ------------------------------------------------
  await progress("Building the gallery…")
  place(gallery(b, { length: 18, depth: 2.5, height: 3.4 }), -7.75, 3, -Math.PI / 2)
  place(staircase(b, { rise: 3.4, width: 1.4 }), -1.5, 12.6, Math.PI)
  const snug = new THREE.Group()
  place(snug, -7.2, 4.5, 0)
  const snugTable = trestleTable(b, { w: 1.6, d: 1.1 })
  snug.add(snugTable)
  const snugClutter = tableClutter(b, { w: 1.6, d: 1.1 })
  snugClutter.position.y = 0.78
  snug.add(snugClutter)
  const settleNorth = highBackBench(b, { len: 1.7 })
  settleNorth.position.set(0, 0, 1.0)
  settleNorth.rotation.y = Math.PI
  snug.add(settleNorth)
  const settleSouth = highBackBench(b, { len: 1.7 })
  settleSouth.position.set(0, 0, -1.0)
  snug.add(settleSouth)
  for (const x of [-2.0, 2.0]) {
    const sheaf = harvestDressing(b)
    sheaf.position.set(x, 0, -0.6)
    snug.add(sheaf)
  }
  // Bram works the door from a host stand just inside it.
  place(hostStand(b), 0, 10.7, 0)
  person("npc-bram", 0, 9.85, 0)

  // ---- hall furniture and patrons ------------------------------------------
  await progress("Seating the crowd…")
  for (const tx of [-3.9, 3.0]) {
    for (let row = 0; row < 6; row++) {
      const tz = -8.5 + row * 3.4 + rng.range(-0.2, 0.2)
      const ry = rng.range(-0.12, 0.12)
      const t = new THREE.Group()
      place(t, tx + rng.range(-0.3, 0.3), tz, ry)
      t.add(trestleTable(b))
      const clutter = tableClutter(b)
      clutter.position.y = 0.78
      t.add(clutter)
      for (const side of [-1, 1]) {
        const seat = bench(b)
        seat.position.set(0, 0, side * 0.72)
        t.add(seat)
        for (const off of [-0.42, 0.42]) {
          if (!rng.chance(0.78)) continue
          someone("seated", off, side * 0.78, side > 0 ? Math.PI : 0, 0, t)
        }
      }
    }
  }
  const standing = (n: number, cx: number, cz: number, spread: number, face: number | null) => {
    for (let i = 0; i < n; i++) {
      const x = cx + rng.range(-spread, spread)
      const z = cz + rng.range(-spread, spread)
      const ry = face === null ? rng.value() * Math.PI * 2 : face + rng.range(-0.5, 0.5)
      someone("standing", x, z, ry)
    }
  }
  standing(7, 6.0, 0.5, 2.4, Math.PI / 2)
  standing(5, 1.5, -10.6, 1.4, Math.PI)
  standing(5, -3.2, -10.2, 1.3, Math.atan2(-5 - -3.2, -12.4 - -10.2))
  standing(3, 2.8, 10.4, 0.9, Math.PI)
  standing(3, -4.5, 10.0, 1.2, null)
  person("server-woman", 1.0, 2.5, 0.9)
  person("server-man", -1.2, -4.0, -2.2)

  // ---- lights and dressing -------------------------------------------------
  await progress("Hanging the lanterns…")
  for (const x of [-3.6, 3.2]) for (const z of [-7.5, 0, 7.5]) place(wheelChandelier(b, { radius: 0.85, chain: 2.0 }), x, z, 0, 4.4)
  for (const z of [-10, -2, 6]) {
    place(wallSconce(b), W / 2 - 0.4, z, -Math.PI / 2, 2.3)
    place(wallSconce(b), -W / 2 + 0.4, z, Math.PI / 2, 2.3)
  }
  for (const x of [-7.5, 6.5]) place(wallSconce(b), x, -D / 2 + 0.4, 0, 2.3)
  root.add(
    bunting(b, [
      { from: V3(-6.6, 4.5, -5.5), to: V3(-6.6, 4.5, 0.5), sag: 0.5, spacing: 0.4 },
      { from: V3(-6.6, 4.5, 0.5), to: V3(-6.6, 4.5, 6.5), sag: 0.5, spacing: 0.4 },
      { from: V3(-6.6, 4.5, 6.5), to: V3(-6.6, 4.5, 11.8), sag: 0.5, spacing: 0.4 },
      { from: V3(-2, 5.6, 13.6), to: V3(2, 5.6, 13.6), sag: 0.4, spacing: 0.4 },
    ])
  )
  for (const [x, z] of [
    [-8.4, -13.2],
    [8.2, 3.6],
    [1.6, 13.3],
    [-1.6, 13.3],
  ])
    place(harvestDressing(b), x, z, rng.value() * 6)

  return {
    id: kordavosDragonboneInn.id,
    title: kordavosDragonboneInn.title,
    root,
    marks: {
      "corner-table": { position: [-7.2, 0, 4.5], facing: 0, label: "The party's snug beneath the gallery" },
      bram: { position: [0, 0, 9.85], facing: 0, label: "Bram at the host stand, facing the doors" },
      bar: { position: [6.2, 0, 0], facing: Math.PI / 2, label: "At the bar, facing the casks" },
      hearthside: { position: [2, 0, -10.5], facing: Math.PI, label: "Before the great hearth" },
      "bard-stage": { position: [-5, 0.22, -12.4], facing: 0.35, label: "The bard's dais" },
      "main-entrance": { position: [0, 0, 12.6], facing: Math.PI, label: "Just inside the street doors" },
    },
    cameras: {
      entrance: { position: [0.35, 1.62, 12.6], target: [0, 1.42, 10.3], label: "Face to face with Bram at the host stand", fov: 42 },
      establishing: { position: [-6.0, 4.6, 10.8], target: [3, 1.2, -7], label: "From the gallery landing across the hall to the hearth", fov: 55 },
      snug: { position: [-3.6, 1.6, 7.8], target: [-7.2, 1.0, 4.5], label: "Across the hall into the party's snug", fov: 42 },
      hearth: { position: [1.5, 1.5, -6.5], target: [-4.2, 1.2, -12.4], label: "Low toward the bard's dais and the firelit crowd", fov: 42 },
      bar: { position: [2.0, 1.6, 4.0], target: [7.2, 1.1, -1], label: "Across the tables to the bar", fov: 40 },
    },
    groundHeight: flatGround,
    environment,
    animated,
    dispose() {
      environment.dispose()
      standees.dispose()
      root.removeFromParent()
    },
  }
}

export const kordavosDragonboneInn: SetDefinition = {
  id: "kordavos-dragonbone-inn",
  title: "The Dragonbone Inn",
  summary:
    "Common room of the Dragonbone Inn: double-height timber hall with hearth and bard's dais, bar and kitchen pass, gallery with the party's snug beneath. Marks: corner-table, bram, bar, hearthside, bard-stage, main-entrance. Cameras: entrance (opening), establishing, snug, hearth, bar. Toggle: timeOfDay (dusk default, night).",
  build,
}
