import type { AdventurePlan } from "@/types/adventure-plan"

export const representativeMyrAdventurePlan: AdventurePlan = {
  id: "the-old-road",
  settingId: "myr",
  title: "The Old Road",
  author: "D20 Adventures",
  version: "legacy-fixture",
  teaser: "A forgotten trade road draws the party toward the gates of Myr.",
  overview: "The party reaches a repaired gatehouse, earns passage, and follows signs of trouble into the market square.",
  party: [1, 4],
  tags: ["myr", "starter"],
  image: "content/settings/myr/adventures/the-old-road/assets/cover.jpg",
  start: "gatehouse-entry",
  nextAdventure: "market-shadows",
  premadePlayerCharacters: [
    {
      id: "vala-apprentice",
      type: "pc",
      name: "Vala's Former Apprentice",
      image: "content/settings/myr/adventures/the-old-road/assets/characters/vala-apprentice.jpg",
      archetype: "Rogue",
      race: "Human",
      appearance: "Quick hands, travel-worn leathers, and a wary look.",
      personality: "Practical and guarded.",
      background: "Once trained by the Gatewarden captain.",
      motivation: "Find out why old friends have gone missing near the road.",
      healthPercent: 100,
      attributes: {
        strength: 8,
        dexterity: 15,
        constitution: 12,
        intelligence: 13,
        wisdom: 10,
        charisma: 14,
      },
      skills: ["Stealth", "Persuasion"],
      equipment: [{ name: "Lockpicks", description: "A compact set of worn tools." }],
      spells: [],
      specialAbilities: ["Gatewarden routines"],
      effects: [],
    },
  ],
  npcs: {
    "captain-vala": {
      id: "captain-vala",
      type: "npc",
      name: "Captain Vala",
      image: "content/settings/myr/assets/portraits/captain-vala.jpg",
      archetype: "Fighter",
      race: "Human",
      appearance: "Tired armor, a steady stance, and an honest face.",
      personality: "Blunt, protective, and increasingly worried.",
      background: "Gatewarden captain responsible for the old road checkpoint.",
      motivation: "Keep frightened travelers from causing a panic.",
      behavior: "Vala asks direct questions and offers help only after the party proves trustworthy.",
      healthPercent: 100,
      attributes: { strength: 12, wisdom: 13 },
    },
  },
  sections: [
    {
      title: "Arrival",
      summary: "The party reaches the old road gatehouse.",
      scenes: [
        {
          title: "Checkpoint",
          summary: "Captain Vala decides whether to let the party through.",
          encounters: [
            {
              id: "gatehouse-entry",
              title: "Gatehouse Entry",
              intro: "The road narrows before a timber gatehouse patched with new stone and old banners.",
              instructions: "Captain Vala is worried, not hostile. She knows the market has become tense and wants a reason to trust the party.",
              image: "content/settings/myr/adventures/the-old-road/assets/encounters/gatehouse-entry.jpg",
              npc: [{ id: "captain-vala", behavior: "Question the party before opening the gate.", initialInitiative: 12 }],
              transitions: [{ condition: "the party earns passage through diplomacy or useful information", encounter: "market-square-arrival" }],
            },
            {
              id: "market-square-arrival",
              title: "Market Square Arrival",
              intro: "Beyond the gate, the market opens into a crowded square where whispers move faster than coin.",
              instructions: "Use this encounter to introduce the first signs that the road trouble reaches into Myr itself.",
              image: "content/settings/myr/adventures/the-old-road/assets/encounters/market-square-arrival.jpg",
              transitions: [],
            },
          ],
        },
      ],
    },
  ],
}
